name: Deploy Master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan 167.172.61.88 >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "$"
          ssh-add - <<< "$"
    - name: Run a one-line script
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: git push root@167.172.61.88:/var/www/html/repo master
